shared:
    image: node:6
jobs:
    main:  
        steps:
            - install: npm install screwdriver-template-main
            # this is run by the PRs as well
            - validate: ./node_modules/.bin/template-validate
    publish:
        requires: [~pr]
        steps:
            - install: npm install screwdriver-template-main
            # publishing also validates
            - publish: ./node_modules/.bin/template-publish
